### ISSUE TITLE
problem with cmake 

### ISSUE THREAD

**Issue by daxiangdaxiang** [DanMcGann/jrl#15]
hi, there,
When I cmake, it shows no such parameter like DJRL_BUILD_PYTHON and ,DJR_PYTHON_VERSION, and the python it finds is not the one in my virtual environment but the default python. How can i solve it?
Thanks very much.

**Comment by DanMcGann** [comment]
Hello!
Sorry you are having trouble with the build setup! Lets see if we can resolve this!

First thing is that JRL does not use a variable named  `JRL_PYTHON_VERSION` so it makes sense that you don't see that.

Second is that the naming convention you imply is not quite right. The CMake variables for python configuration is `JRL_BUILD_PYTHON`. When setting these variables from the command line you use the CMake command line option `-D` so the full command becomes something like  `cmake .. -D JRL_BUILD_PYTHON=On` HOWEVER, CMake is stringly typed so you need to omit the space (` `) between `-D` and `JRL...` Thus to set these variables when running CMake from the command like is: `cmake .. -DJRL_BUILD_PYTHON=On`

A useful thing to debug is to use the visual CMake interface to view what variables are used by the build system and what their values are by running `ccmake  build/`.

Finally, it sounds like you are managing to enable building of python given you specify that CMake is finding the system python. This just means that you want to fix the install to find a virtual environment version. If you are using the `development` version of the code you can fix this with the following steps:

```
# Uninstall steps may be unnecessary if you have not installed anything
cd build/
make jrl-uninstall 
make jrl-python-uninstall

rm -rf build/ # completely remove the build since CMake will have cached incorrect python setting
conda activate myenv # Or the proper activation for your virtual environment

# Build JRL with python and install the python bindings python
mkdir build
cd build
cmake .. -DJRL_BUILD_PYTHON=On
make
make jrl-python-install
```

With this you should be able to test it by (with the virtual env running)
```
python
# Wait for Interpreter to start
import jrl 
```

Last note: If the steps above do not resolve the issue please provide:
1. JRL version you are using (exact commit hash)
2. Output from `cmake ..`  from build directory
3. Output of `cmake -LAH`  from build directory

Best -Dan

**Comment by DanMcGann** [comment]
Closing as solved given no followup.

**Comment by daxiangdaxiang** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DanMcGann/jrl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月26日(星期一) 晚上11:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DanMcGann/jrl] problem with cmake  (Issue #15)





 
Hello!
 Sorry you are having trouble with the build setup! Lets see if we can resolve this!
 
First thing is that JRL does not use a variable named  JRL_PYTHON_VERSION so it makes sense that you don't see that.
 
Second is that the naming convention you imply is not quite right. The CMake variables for python configuration is JRL_BUILD_PYTHON. When setting these variables from the command line you use the CMake command line option -D so the full command becomes something like  cmake .. -D JRL_BUILD_PYTHON=On HOWEVER, CMake is stringly typed so you need to omit the space ( ) between -D and JRL... Thus to set these variables when running CMake from the command like is: cmake .. -DJRL_BUILD_PYTHON=On
 
A useful thing to debug is to use the visual CMake interface to view what variables are used by the build system and what their values are by running ccmake  build/.
 
Finally, it sounds like you are managing to enable building of python given you specify that CMake is finding the system python. This just means that you want to fix the install to find a virtual environment version. If you are using the development version of the code you can fix this with the following steps:
 # Uninstall steps may be unnecessary if you have not installed anything cd build/ make jrl-uninstall  make jrl-python-uninstall rm -rf build/ # completely remove the build since CMake will have cached incorrect python setting conda activate myenv # Or the proper activation for your virtual environment # Build JRL with python and install the python bindings python mkdir build cd build cmake .. -DJRL_BUILD_PYTHON=On make make jrl-python-install  
With this you should be able to test it by (with the virtual env running)
 python # Wait for Interpreter to start import jrl   
Last note: If the steps above do not resolve the issue please provide:
  
JRL version you are using (exact commit hash)
 
Output from cmake ..  from build directory
 
Output of cmake -LAH  from build directory
  
Best -Dan

**Comment by daxiangdaxiang** [comment]
Dear Dan,



I hope this message finds you well. I wanted to sincerely thank you for taking the time to answer my technical question on GitHub. Your explanation was incredibly helpful and clarified a lot of my doubts. I truly appreciate your expertise and willingness to assist.

I also wanted to apologize for the delay in my response. I accidentally missed the email notification and only recently realized that you had replied. I’m sorry for any inconvenience this may have caused.

Thank you again for your support, and I’m grateful for your patience.



Best regards,
Ethan
------------------ 原始邮件 ------------------
发件人:                                                                                                                        "DanMcGann/jrl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月26日(星期一) 晚上11:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DanMcGann/jrl] problem with cmake  (Issue #15)





 
Hello!
 Sorry you are having trouble with the build setup! Lets see if we can resolve this!
 
First thing is that JRL does not use a variable named  JRL_PYTHON_VERSION so it makes sense that you don't see that.
 
Second is that the naming convention you imply is not quite right. The CMake variables for python configuration is JRL_BUILD_PYTHON. When setting these variables from the command line you use the CMake command line option -D so the full command becomes something like  cmake .. -D JRL_BUILD_PYTHON=On HOWEVER, CMake is stringly typed so you need to omit the space ( ) between -D and JRL... Thus to set these variables when running CMake from the command like is: cmake .. -DJRL_BUILD_PYTHON=On
 
A useful thing to debug is to use the visual CMake interface to view what variables are used by the build system and what their values are by running ccmake  build/.
 
Finally, it sounds like you are managing to enable building of python given you specify that CMake is finding the system python. This just means that you want to fix the install to find a virtual environment version. If you are using the development version of the code you can fix this with the following steps:
 # Uninstall steps may be unnecessary if you have not installed anything cd build/ make jrl-uninstall  make jrl-python-uninstall rm -rf build/ # completely remove the build since CMake will have cached incorrect python setting conda activate myenv # Or the proper activation for your virtual environment # Build JRL with python and install the python bindings python mkdir build cd build cmake .. -DJRL_BUILD_PYTHON=On make make jrl-python-install  
With this you should be able to test it by (with the virtual env running)
 python # Wait for Interpreter to start import jrl   
Last note: If the steps above do not resolve the issue please provide:
  
JRL version you are using (exact commit hash)
 
Output from cmake ..  from build directory
 
Output of cmake -LAH  from build directory
  
Best -Dan
